# prefixキーをC-tに変更
#set -g prefix C-t

# C-bのキーバインドを解除
#unbind C-b

#set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'
set -g default-terminal "xterm-256color"

# Plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-sensible'

#set -g @plugin 'dracula/tmux'
#set -g @dracula-plugins 'battery cpu-usage ram-usage weather time'
set -g status-right ""

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @resurrect-strategy-vim 'session'
set -g @continuum-restore 'on'

# vimのキーバインドでペインを移動する
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# vimのキーバインドでペインをリサイズする
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# | でペインを縦分割する
bind | split-window -h

# | でペインを縦分割する
bind - split-window -v

# 番号基準値を変更
set-option -g base-index 1

# マウス操作を有効にする
set-option -g mouse on

# コピーモードを設定する
setw -g mode-keys vi

# デフォルトのshellをbash明示的に指定する
set-option -g default-shell /bin/bash

# ---------------------------------------------------------
# initialize tmux plugin manager
# ---------------------------------------------------------

run '~/.tmux/plugins/tpm/tpm'

# ---------------------------------------------------------
# Link with windows clipboard
# ---------------------------------------------------------
# vimのキーバインドを使う場合
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "win32yank.exe -i"
bind p run-shell 'win32yank.exe -o | xargs -0 -I{} tmux set-buffer -- {} && tmux paste-buffer'


# ---------------------------------------------------------
# Adjust the appearance of the status line
# ---------------------------------------------------------
set -g mode-style "bg=#264f78,fg=#ffffff"
set -g message-style "fg=#eee8d5,bg=#073642"
set -g message-command-style "fg=#eee8d5,bg=#073642"

set -g pane-border-style "fg=#073642"
set -g pane-active-border-style "fg=#eee8d5"

set -g status-style "fg=#586e75,bg=#073642"
set -g status-bg "#002b36"
setw -g window-status-activity-style "underscore,fg=#839496,bg=#002b36"

set -g window-status-style "fg=default,bg=#282a36"
set -g window-status-separator " "

# The characters displayed on the left and right sides of each window in the status line
# are the following glyphs (requires Nerd Font):
#
# - Left: 0xe0b6
# - Right: 0xe0b4
#
# When pasting via the clipboard, the glyphs may become corrupted.
# Therefore, use placeholders at the positions where the glyphs should be displayed:
#
# - Left: @L@
# - Right: @R@
#
# After that, run the following commands in Vim to replace the placeholders
# with the corresponding glyphs:
#
# - Left: :%s/@L@/\=nr2char(0xe0b6)/g
# - Right: :%s/@R@/\=nr2char(0xe0b4)/g
set -g window-status-format "#[fg=#90A4AE,bg=#282a36]#[fg=#282a36,bg=#90A4AE] #I #[fg=#f8f8f2,bg=#44475a] #W #[fg=#44475a,bg=#282a36]"
set -g window-status-current-format "#[fg=#bf1d64,bg=#282a36]#[fg=#f8f8f2,bg=#bf1d64] #I #[fg=#f8f8f2,bg=#44475a] #W #[fg=#44475a,bg=#282a36]"

# ---------------------------------------------------------
# Key-bindings for swap pane
# ---------------------------------------------------------
bind-key -T root C-q switch-client -T my-keys
bind-key -T my-keys C-p switch-client -T my-keys-pane-ctl
bind-key -T my-keys-pane-ctl s command-prompt -p "Target pane: " "swap-pane -t '%%'"
bind-key -T my-keys-pane-ctl Escape switch-client -T root
bind-key -T my-keys Escape switch-client -T root


bind-key t select-layout tiled
bind-key u resize-pane -U 999
bind-key d resize-pane -D 999
bind-key x detach-client

bind-key m command-prompt -p "Swap with pane #:" "swap-pane -t '%%'"
